/*
 This file is automatically generated by tool/meta.PL.
 */
// module meta
"use strict";
// auto-generated constants
/** @enum {int} */
var C = {
// metadata.h
  ASSEMBLY_HASH_ALG                : 0x0, // 0
  ASSEMBLY_PROCESSOR               : 0x0, // 0
  ASSEMBLY_MAJOR_VERSION           : 0x1, // 1
  ASSEMBLY_PROCESSOR_SIZE          : 0x1, // 1
  ASSEMBLY_MINOR_VERSION           : 0x2, // 2
  ASSEMBLY_BUILD_NUMBER            : 0x3, // 3
  ASSEMBLY_REV_NUMBER              : 0x4, // 4
  ASSEMBLY_FLAGS                   : 0x5, // 5
  ASSEMBLY_PUBLIC_KEY              : 0x6, // 6
  ASSEMBLY_NAME                    : 0x7, // 7
  ASSEMBLY_CULTURE                 : 0x8, // 8
  ASSEMBLY_SIZE                    : 0x9, // 9
  ASSEMBLYOS_PLATFORM              : 0x0, // 0
  ASSEMBLYOS_MAJOR_VERSION         : 0x1, // 1
  ASSEMBLYOS_MINOR_VERSION         : 0x2, // 2
  ASSEMBLYOS_SIZE                  : 0x3, // 3
  ASSEMBLYREF_MAJOR_VERSION        : 0x0, // 0
  ASSEMBLYREF_MINOR_VERSION        : 0x1, // 1
  ASSEMBLYREF_BUILD_NUMBER         : 0x2, // 2
  ASSEMBLYREF_REV_NUMBER           : 0x3, // 3
  ASSEMBLYREF_FLAGS                : 0x4, // 4
  ASSEMBLYREF_PUBLIC_KEY           : 0x5, // 5
  ASSEMBLYREF_NAME                 : 0x6, // 6
  ASSEMBLYREF_CULTURE              : 0x7, // 7
  ASSEMBLYREF_HASH_VALUE           : 0x8, // 8
  ASSEMBLYREF_SIZE                 : 0x9, // 9
  ASSEMBLYREFOS_PLATFORM           : 0x0, // 0
  ASSEMBLYREFOS_MAJOR_VERSION      : 0x1, // 1
  ASSEMBLYREFOS_MINOR_VERSION      : 0x2, // 2
  ASSEMBLYREFOS_ASSEMBLYREF        : 0x3, // 3
  ASSEMBLYREFOS_SIZE               : 0x4, // 4
  ASSEMBLYREFPROC_PROCESSOR        : 0x0, // 0
  ASSEMBLYREFPROC_ASSEMBLYREF      : 0x1, // 1
  ASSEMBLYREFPROC_SIZE             : 0x2, // 2
  BEGIN_DECLS                      : 0x1, // 1
  CALL_DEFAULT                     : 0x0, // 0
  CALL_C                           : 0x1, // 1
  CALL_STDCALL                     : 0x2, // 2
  CALL_THISCALL                    : 0x3, // 3
  CALL_FASTCALL                    : 0x4, // 4
  CALL_VARARG                      : 0x5, // 5
  CLASS_LAYOUT_PACKING_SIZE        : 0x0, // 0
  CLASS_LAYOUT_CLASS_SIZE          : 0x1, // 1
  CLASS_LAYOUT_PARENT              : 0x2, // 2
  CLASS_LAYOUT_SIZE                : 0x3, // 3
  CONSTANT_TYPE                    : 0x0, // 0
  CONSTANT_PADDING                 : 0x1, // 1
  CONSTANT_PARENT                  : 0x2, // 2
  CONSTANT_VALUE                   : 0x3, // 3
  CONSTANT_SIZE                    : 0x4, // 4
  CUSTOM_ATTR_METHODDEF            : 0x0, // 0
  CUSTOM_ATTR_PARENT               : 0x0, // 0
  CUSTOM_ATTR_TYPE_TYPEREF         : 0x0, // 0
  CUSTOM_ATTR_FIELDDEF             : 0x1, // 1
  CUSTOM_ATTR_TYPE                 : 0x1, // 1
  CUSTOM_ATTR_TYPE_TYPEDEF         : 0x1, // 1
  CUSTOM_ATTR_TYPEREF              : 0x2, // 2
  CUSTOM_ATTR_TYPE_METHODDEF       : 0x2, // 2
  CUSTOM_ATTR_VALUE                : 0x2, // 2
  CUSTOM_ATTR_SIZE                 : 0x3, // 3
  CUSTOM_ATTR_TYPEDEF              : 0x3, // 3
  CUSTOM_ATTR_TYPE_BITS            : 0x3, // 3
  CUSTOM_ATTR_TYPE_MEMBERREF       : 0x3, // 3
  CUSTOM_ATTR_PARAMDEF             : 0x4, // 4
  CUSTOM_ATTR_TYPE_STRING          : 0x4, // 4
  CUSTOM_ATTR_BITS                 : 0x5, // 5
  CUSTOM_ATTR_INTERFACE            : 0x5, // 5
  CUSTOM_ATTR_MEMBERREF            : 0x6, // 6
  CUSTOM_ATTR_MODULE               : 0x7, // 7
  CUSTOM_ATTR_TYPE_MASK            : 0x7, // 7
  CUSTOM_ATTR_PERMISSION           : 0x8, // 8
  CUSTOM_ATTR_PROPERTY             : 0x9, // 9
  CUSTOM_ATTR_EVENT                : 0xa, // 10
  CUSTOM_ATTR_SIGNATURE            : 0xb, // 11
  CUSTOM_ATTR_MODULEREF            : 0xc, // 12
  CUSTOM_ATTR_TYPESPEC             : 0xd, // 13
  CUSTOM_ATTR_ASSEMBLY             : 0xe, // 14
  CUSTOM_ATTR_ASSEMBLYREF          : 0xf, // 15
  CUSTOM_ATTR_FILE                 : 0x10, // 16
  CUSTOM_ATTR_EXP_TYPE             : 0x11, // 17
  CUSTOM_ATTR_MANIFEST             : 0x12, // 18
  CUSTOM_ATTR_GENERICPAR           : 0x13, // 19
  CUSTOM_ATTR_MASK                 : 0x1f, // 31
  DECL_SECURITY_ACTION             : 0x0, // 0
  DECL_SECURITY_PARENT             : 0x1, // 1
  DECL_SECURITY_PERMISSIONSET      : 0x2, // 2
  DECL_SECURITY_SIZE               : 0x3, // 3
  END_DECLS                        : 0x1, // 1
  EVENT_FLAGS                      : 0x0, // 0
  EVENT_MAP_PARENT                 : 0x0, // 0
  EVENT_POINTER_EVENT              : 0x0, // 0
  EVENT_MAP_EVENTLIST              : 0x1, // 1
  EVENT_NAME                       : 0x1, // 1
  EVENT_POINTER_SIZE               : 0x1, // 1
  EVENT_MAP_SIZE                   : 0x2, // 2
  EVENT_TYPE                       : 0x2, // 2
  EVENT_SIZE                       : 0x3, // 3
  EXCEPTION_CLAUSE_NONE            : 0x0, // 0
  EXCEPTION_CLAUSE_FILTER          : 0x1, // 1
  EXCEPTION_CLAUSE_FINALLY         : 0x2, // 2
  EXCEPTION_CLAUSE_FAULT           : 0x4, // 4
  EXP_TYPE_FLAGS                   : 0x0, // 0
  EXP_TYPE_TYPEDEF                 : 0x1, // 1
  EXP_TYPE_NAME                    : 0x2, // 2
  EXP_TYPE_NAMESPACE               : 0x3, // 3
  EXP_TYPE_IMPLEMENTATION          : 0x4, // 4
  EXP_TYPE_SIZE                    : 0x5, // 5
  FIELD_FLAGS                      : 0x0, // 0
  FIELD_LAYOUT_OFFSET              : 0x0, // 0
  FIELD_MARSHAL_PARENT             : 0x0, // 0
  FIELD_POINTER_FIELD              : 0x0, // 0
  FIELD_RVA_RVA                    : 0x0, // 0
  FIELD_LAYOUT_FIELD               : 0x1, // 1
  FIELD_MARSHAL_NATIVE_TYPE        : 0x1, // 1
  FIELD_NAME                       : 0x1, // 1
  FIELD_POINTER_SIZE               : 0x1, // 1
  FIELD_RVA_FIELD                  : 0x1, // 1
  FIELD_LAYOUT_SIZE                : 0x2, // 2
  FIELD_MARSHAL_SIZE               : 0x2, // 2
  FIELD_RVA_SIZE                   : 0x2, // 2
  FIELD_SIGNATURE                  : 0x2, // 2
  FIELD_SIZE                       : 0x3, // 3
  FILE_FLAGS                       : 0x0, // 0
  FILE_NAME                        : 0x1, // 1
  FILE_HASH_VALUE                  : 0x2, // 2
  FILE_SIZE                        : 0x3, // 3
  GENERICPARAM_NUMBER              : 0x0, // 0
  GENERICPARAM_FLAGS               : 0x1, // 1
  GENERICPARAM_OWNER               : 0x2, // 2
  GENERICPARAM_NAME                : 0x3, // 3
  GENERICPARAM_SIZE                : 0x4, // 4
  GENPARCONSTRAINT_GENERICPAR      : 0x0, // 0
  GENPARCONSTRAINT_CONSTRAINT      : 0x1, // 1
  GENPARCONSTRAINT_SIZE            : 0x2, // 2
  HAS_DECL_SECURITY_TYPEDEF        : 0x0, // 0
  HAS_FIELD_MARSHAL_FIELDSREF      : 0x0, // 0
  HAS_SEMANTICS_EVENT              : 0x0, // 0
  HAS_DECL_SECURITY_METHODDEF      : 0x1, // 1
  HAS_FIELD_MARSHAL_BITS           : 0x1, // 1
  HAS_FIELD_MARSHAL_MASK           : 0x1, // 1
  HAS_FIELD_MARSHAL_PARAMDEF       : 0x1, // 1
  HAS_SEMANTICS_BITS               : 0x1, // 1
  HAS_SEMANTICS_MASK               : 0x1, // 1
  HAS_SEMANTICS_PROPERTY           : 0x1, // 1
  HAS_DECL_SECURITY_ASSEMBLY       : 0x2, // 2
  HAS_DECL_SECURITY_BITS           : 0x2, // 2
  HAS_DECL_SECURITY_MASK           : 0x3, // 3
  HASCONSTANT_FIEDDEF              : 0x0, // 0
  HASCONSTANT_PARAM                : 0x1, // 1
  HASCONSTANT_BITS                 : 0x2, // 2
  HASCONSTANT_PROPERTY             : 0x2, // 2
  HASCONSTANT_MASK                 : 0x3, // 3
  IMAGE_OK                         : 0x0, // 0
  IMAGE_ERROR_ERRNO                : 0x1, // 1
  IMAGE_MISSING_ASSEMBLYREF        : 0x2, // 2
  IMAGE_IMAGE_INVALID              : 0x3, // 3
  IMPLEMENTATION_FILE              : 0x0, // 0
  IMPLEMENTATION_ASSEMBLYREF       : 0x1, // 1
  IMPLEMENTATION_BITS              : 0x2, // 2
  IMPLEMENTATION_EXP_TYPE          : 0x2, // 2
  IMPLEMENTATION_MASK              : 0x3, // 3
  IMPLMAP_FLAGS                    : 0x0, // 0
  IMPLMAP_MEMBER                   : 0x1, // 1
  IMPLMAP_NAME                     : 0x2, // 2
  IMPLMAP_SCOPE                    : 0x3, // 3
  IMPLMAP_SIZE                     : 0x4, // 4
  INTERFACEIMPL_CLASS              : 0x0, // 0
  INTERFACEIMPL_INTERFACE          : 0x1, // 1
  INTERFACEIMPL_SIZE               : 0x2, // 2
  MANIFEST_OFFSET                  : 0x0, // 0
  MANIFEST_FLAGS                   : 0x1, // 1
  MANIFEST_NAME                    : 0x2, // 2
  MANIFEST_IMPLEMENTATION          : 0x3, // 3
  MANIFEST_SIZE                    : 0x4, // 4
  MARSHAL_CONV_NONE                : 0x0, // 0
  MARSHAL_CONV_BOOL_VARIANTBOOL    : 0x1, // 1
  MARSHAL_CONV_BOOL_I4             : 0x2, // 2
  MARSHAL_CONV_STR_BSTR            : 0x3, // 3
  MARSHAL_CONV_STR_LPSTR           : 0x4, // 4
  MARSHAL_CONV_LPSTR_STR           : 0x5, // 5
  MARSHAL_CONV_LPTSTR_STR          : 0x6, // 6
  MARSHAL_CONV_STR_LPWSTR          : 0x7, // 7
  MARSHAL_CONV_LPWSTR_STR          : 0x8, // 8
  MARSHAL_CONV_STR_LPTSTR          : 0x9, // 9
  MARSHAL_CONV_STR_ANSIBSTR        : 0xa, // 10
  MARSHAL_CONV_STR_TBSTR           : 0xb, // 11
  MARSHAL_CONV_STR_BYVALSTR        : 0xc, // 12
  MARSHAL_CONV_STR_BYVALWSTR       : 0xd, // 13
  MARSHAL_CONV_SB_LPSTR            : 0xe, // 14
  MARSHAL_CONV_SB_LPTSTR           : 0xf, // 15
  MARSHAL_CONV_SB_LPWSTR           : 0x10, // 16
  MARSHAL_CONV_LPSTR_SB            : 0x11, // 17
  MARSHAL_CONV_LPTSTR_SB           : 0x12, // 18
  MARSHAL_CONV_LPWSTR_SB           : 0x13, // 19
  MARSHAL_CONV_ARRAY_BYVALARRAY    : 0x14, // 20
  MARSHAL_CONV_ARRAY_BYVALCHARARRAY: 0x15, // 21
  MARSHAL_CONV_ARRAY_SAVEARRAY     : 0x16, // 22
  MARSHAL_CONV_ARRAY_LPARRAY       : 0x17, // 23
  MARSHAL_FREE_LPARRAY             : 0x18, // 24
  MARSHAL_CONV_OBJECT_INTERFACE    : 0x19, // 25
  MARSHAL_CONV_OBJECT_IDISPATCH    : 0x1a, // 26
  MARSHAL_CONV_OBJECT_IUNKNOWN     : 0x1b, // 27
  MARSHAL_CONV_OBJECT_STRUCT       : 0x1c, // 28
  MARSHAL_CONV_DEL_FTN             : 0x1d, // 29
  MARSHAL_CONV_FTN_DEL             : 0x1e, // 30
  MARSHAL_FREE_ARRAY               : 0x1f, // 31
  MARSHAL_CONV_BSTR_STR            : 0x20, // 32
  MARSHAL_CONV_SAFEHANDLE          : 0x21, // 33
  MARSHAL_CONV_HANDLEREF           : 0x22, // 34
  MEMBERFORWD_FIELDDEF             : 0x0, // 0
  MEMBERFORWD_BITS                 : 0x1, // 1
  MEMBERFORWD_MASK                 : 0x1, // 1
  MEMBERFORWD_METHODDEF            : 0x1, // 1
  MEMBERREF_CLASS                  : 0x0, // 0
  MEMBERREF_PARENT_TYPEDEF         : 0x0, // 0
  MEMBERREF_NAME                   : 0x1, // 1
  MEMBERREF_PARENT_TYPEREF         : 0x1, // 1
  MEMBERREF_PARENT_MODULEREF       : 0x2, // 2
  MEMBERREF_SIGNATURE              : 0x2, // 2
  MEMBERREF_PARENT_BITS            : 0x3, // 3
  MEMBERREF_PARENT_METHODDEF       : 0x3, // 3
  MEMBERREF_SIZE                   : 0x3, // 3
  MEMBERREF_PARENT_TYPESPEC        : 0x4, // 4
  MEMBERREF_PARENT_MASK            : 0x7, // 7
  METHOD_POINTER_METHOD            : 0x0, // 0
  METHOD_RVA                       : 0x0, // 0
  METHOD_SEMA_SEMANTICS            : 0x0, // 0
  METHOD_IMPLFLAGS                 : 0x1, // 1
  METHOD_POINTER_SIZE              : 0x1, // 1
  METHOD_SEMA_METHOD               : 0x1, // 1
  METHOD_FLAGS                     : 0x2, // 2
  METHOD_SEMA_ASSOCIATION          : 0x2, // 2
  METHOD_NAME                      : 0x3, // 3
  METHOD_SEMA_SIZE                 : 0x3, // 3
  METHOD_SIGNATURE                 : 0x4, // 4
  METHOD_PARAMLIST                 : 0x5, // 5
  METHOD_SIZE                      : 0x6, // 6
  METHODDEFORREF_METHODDEF         : 0x0, // 0
  METHODDEFORREF_BITS              : 0x1, // 1
  METHODDEFORREF_MASK              : 0x1, // 1
  METHODDEFORREF_METHODREF         : 0x1, // 1
  METHODIMPL_CLASS                 : 0x0, // 0
  METHODIMPL_BODY                  : 0x1, // 1
  METHODIMPL_DECLARATION           : 0x2, // 2
  METHODIMPL_SIZE                  : 0x3, // 3
  METHODSPEC_METHOD                : 0x0, // 0
  METHODSPEC_SIGNATURE             : 0x1, // 1
  METHODSPEC_SIZE                  : 0x2, // 2
  MODULE_GENERATION                : 0x0, // 0
  MODULE_NAME                      : 0x1, // 1
  MODULE_MVID                      : 0x2, // 2
  MODULE_ENC                       : 0x3, // 3
  MODULE_ENCBASE                   : 0x4, // 4
  MODULE_SIZE                      : 0x5, // 5
  MODULEREF_NAME                   : 0x0, // 0
  MODULEREF_SIZE                   : 0x1, // 1
  NATIVE_BOOLEAN                   : 0x2, // 2
  NATIVE_I1                        : 0x3, // 3
  NATIVE_U1                        : 0x4, // 4
  NATIVE_I2                        : 0x5, // 5
  NATIVE_U2                        : 0x6, // 6
  NATIVE_I4                        : 0x7, // 7
  NATIVE_U4                        : 0x8, // 8
  NATIVE_I8                        : 0x9, // 9
  NATIVE_U8                        : 0xa, // 10
  NATIVE_R4                        : 0xb, // 11
  NATIVE_R8                        : 0xc, // 12
  NATIVE_CURRENCY                  : 0xf, // 15
  NATIVE_BSTR                      : 0x13, // 19
  NATIVE_LPSTR                     : 0x14, // 20
  NATIVE_LPWSTR                    : 0x15, // 21
  NATIVE_LPTSTR                    : 0x16, // 22
  NATIVE_BYVALTSTR                 : 0x17, // 23
  NATIVE_IUNKNOWN                  : 0x19, // 25
  NATIVE_IDISPATCH                 : 0x1a, // 26
  NATIVE_STRUCT                    : 0x1b, // 27
  NATIVE_INTERFACE                 : 0x1c, // 28
  NATIVE_SAFEARRAY                 : 0x1d, // 29
  NATIVE_BYVALARRAY                : 0x1e, // 30
  NATIVE_INT                       : 0x1f, // 31
  NATIVE_UINT                      : 0x20, // 32
  NATIVE_VBBYREFSTR                : 0x22, // 34
  NATIVE_ANSIBSTR                  : 0x23, // 35
  NATIVE_TBSTR                     : 0x24, // 36
  NATIVE_VARIANTBOOL               : 0x25, // 37
  NATIVE_FUNC                      : 0x26, // 38
  NATIVE_ASANY                     : 0x28, // 40
  NATIVE_LPARRAY                   : 0x2a, // 42
  NATIVE_LPSTRUCT                  : 0x2b, // 43
  NATIVE_CUSTOM                    : 0x2c, // 44
  NATIVE_ERROR                     : 0x2d, // 45
  NATIVE_MAX                       : 0x50, // 80
  NESTED_CLASS_NESTED              : 0x0, // 0
  NESTED_CLASS_ENCLOSING           : 0x1, // 1
  NESTED_CLASS_SIZE                : 0x2, // 2
  PARAM_FLAGS                      : 0x0, // 0
  PARAM_POINTER_PARAM              : 0x0, // 0
  PARAM_POINTER_SIZE               : 0x1, // 1
  PARAM_SEQUENCE                   : 0x1, // 1
  PARAM_NAME                       : 0x2, // 2
  PARAM_SIZE                       : 0x3, // 3
  PARSE_TYPE                       : 0x0, // 0
  PARSE_MOD_TYPE                   : 0x1, // 1
  PARSE_LOCAL                      : 0x2, // 2
  PARSE_PARAM                      : 0x3, // 3
  PARSE_RET                        : 0x4, // 4
  PARSE_FIELD                      : 0x5, // 5
  PROPERTY_FLAGS                   : 0x0, // 0
  PROPERTY_MAP_PARENT              : 0x0, // 0
  PROPERTY_POINTER_PROPERTY        : 0x0, // 0
  PROPERTY_MAP_PROPERTY_LIST       : 0x1, // 1
  PROPERTY_NAME                    : 0x1, // 1
  PROPERTY_POINTER_SIZE            : 0x1, // 1
  PROPERTY_MAP_SIZE                : 0x2, // 2
  PROPERTY_TYPE                    : 0x2, // 2
  PROPERTY_SIZE                    : 0x3, // 3
  RESOLTION_SCOPE_MODULE           : 0x0, // 0
  RESOLTION_SCOPE_MODULEREF        : 0x1, // 1
  RESOLTION_SCOPE_ASSEMBLYREF      : 0x2, // 2
  RESOLTION_SCOPE_BITS             : 0x2, // 2
  RESOLTION_SCOPE_MASK             : 0x3, // 3
  RESOLTION_SCOPE_TYPEREF          : 0x3, // 3
  STAND_ALONE_SIGNATURE            : 0x0, // 0
  STAND_ALONE_SIGNATURE_SIZE       : 0x1, // 1
  TABLE_MODULE                     : 0x0, // 0
  TABLE_TYPEREF                    : 0x1, // 1
  TABLE_TYPEDEF                    : 0x2, // 2
  TABLE_FIELD_POINTER              : 0x3, // 3
  TABLE_FIELD                      : 0x4, // 4
  TABLE_METHOD_POINTER             : 0x5, // 5
  TABLE_METHOD                     : 0x6, // 6
  TABLE_PARAM_POINTER              : 0x7, // 7
  TABLE_PARAM                      : 0x8, // 8
  TABLE_INTERFACEIMPL              : 0x9, // 9
  TABLE_MEMBERREF                  : 0xa, // 10
  TABLE_CONSTANT                   : 0xb, // 11
  TABLE_CUSTOMATTRIBUTE            : 0xc, // 12
  TABLE_FIELDMARSHAL               : 0xd, // 13
  TABLE_DECLSECURITY               : 0xe, // 14
  TABLE_CLASSLAYOUT                : 0xf, // 15
  TABLE_FIELDLAYOUT                : 0x10, // 16
  TABLE_STANDALONESIG              : 0x11, // 17
  TABLE_EVENTMAP                   : 0x12, // 18
  TABLE_EVENT_POINTER              : 0x13, // 19
  TABLE_EVENT                      : 0x14, // 20
  TABLE_PROPERTYMAP                : 0x15, // 21
  TABLE_PROPERTY_POINTER           : 0x16, // 22
  TABLE_PROPERTY                   : 0x17, // 23
  TABLE_METHODSEMANTICS            : 0x18, // 24
  TABLE_METHODIMPL                 : 0x19, // 25
  TABLE_MODULEREF                  : 0x1a, // 26
  TABLE_TYPESPEC                   : 0x1b, // 27
  TABLE_IMPLMAP                    : 0x1c, // 28
  TABLE_FIELDRVA                   : 0x1d, // 29
  TABLE_UNUSED6                    : 0x1e, // 30
  TABLE_UNUSED7                    : 0x1f, // 31
  TABLE_ASSEMBLY                   : 0x20, // 32
  TABLE_ASSEMBLYPROCESSOR          : 0x21, // 33
  TABLE_ASSEMBLYOS                 : 0x22, // 34
  TABLE_ASSEMBLYREF                : 0x23, // 35
  TABLE_ASSEMBLYREFPROCESSOR       : 0x24, // 36
  TABLE_ASSEMBLYREFOS              : 0x25, // 37
  TABLE_FILE                       : 0x26, // 38
  TABLE_EXPORTEDTYPE               : 0x27, // 39
  TABLE_MANIFESTRESOURCE           : 0x28, // 40
  TABLE_NESTEDCLASS                : 0x29, // 41
  TABLE_GENERICPARAM               : 0x2a, // 42
  TABLE_METHODSPEC                 : 0x2b, // 43
  TABLE_GENERICPARAMCONSTRAINT     : 0x2c, // 44
  TABLE_LAST                       : 0x2c, // 44
  TYPE_END                         : 0x0, // 0
  TYPE_VOID                        : 0x1, // 1
  TYPE_BOOLEAN                     : 0x2, // 2
  TYPE_CHAR                        : 0x3, // 3
  TYPE_I1                          : 0x4, // 4
  TYPE_U1                          : 0x5, // 5
  TYPE_I2                          : 0x6, // 6
  TYPE_U2                          : 0x7, // 7
  TYPE_I4                          : 0x8, // 8
  TYPE_U4                          : 0x9, // 9
  TYPE_I8                          : 0xa, // 10
  TYPE_U8                          : 0xb, // 11
  TYPE_R4                          : 0xc, // 12
  TYPE_R8                          : 0xd, // 13
  TYPE_STRING                      : 0xe, // 14
  TYPE_PTR                         : 0xf, // 15
  TYPE_BYREF                       : 0x10, // 16
  TYPE_VALUETYPE                   : 0x11, // 17
  TYPE_CLASS                       : 0x12, // 18
  TYPE_VAR                         : 0x13, // 19
  TYPE_ARRAY                       : 0x14, // 20
  TYPE_GENERICINST                 : 0x15, // 21
  TYPE_TYPEDBYREF                  : 0x16, // 22
  TYPE_I                           : 0x18, // 24
  TYPE_U                           : 0x19, // 25
  TYPE_FNPTR                       : 0x1b, // 27
  TYPE_OBJECT                      : 0x1c, // 28
  TYPE_SZARRAY                     : 0x1d, // 29
  TYPE_MVAR                        : 0x1e, // 30
  TYPE_CMOD_REQD                   : 0x1f, // 31
  TYPE_CMOD_OPT                    : 0x20, // 32
  TYPE_INTERNAL                    : 0x21, // 33
  TYPE_MODIFIER                    : 0x40, // 64
  TYPE_SENTINEL                    : 0x41, // 65
  TYPE_PINNED                      : 0x45, // 69
  TYPE_ENUM                        : 0x55, // 85
  TYPEDEF_FLAGS                    : 0x0, // 0
  TYPEDEF_NAME                     : 0x1, // 1
  TYPEDEF_NAMESPACE                : 0x2, // 2
  TYPEDEF_EXTENDS                  : 0x3, // 3
  TYPEDEF_FIELD_LIST               : 0x4, // 4
  TYPEDEF_METHOD_LIST              : 0x5, // 5
  TYPEDEF_SIZE                     : 0x6, // 6
  TYPEDEFORREF_TYPEDEF             : 0x0, // 0
  TYPEDEFORREF_TYPEREF             : 0x1, // 1
  TYPEDEFORREF_BITS                : 0x2, // 2
  TYPEDEFORREF_TYPESPEC            : 0x2, // 2
  TYPEDEFORREF_MASK                : 0x3, // 3
  TYPEORMETHOD_TYPE                : 0x0, // 0
  TYPEORMETHOD_BITS                : 0x1, // 1
  TYPEORMETHOD_MASK                : 0x1, // 1
  TYPEORMETHOD_METHOD              : 0x1, // 1
  TYPEREF_SCOPE                    : 0x0, // 0
  TYPEREF_NAME                     : 0x1, // 1
  TYPEREF_NAMESPACE                : 0x2, // 2
  TYPEREF_SIZE                     : 0x3, // 3
  TYPESPEC_SIGNATURE               : 0x0, // 0
  TYPESPEC_SIZE                    : 0x1, // 1
  VARIANT_EMPTY                    : 0x0, // 0
  VARIANT_NULL                     : 0x1, // 1
  VARIANT_I2                       : 0x2, // 2
  VARIANT_I4                       : 0x3, // 3
  VARIANT_R4                       : 0x4, // 4
  VARIANT_R8                       : 0x5, // 5
  VARIANT_CY                       : 0x6, // 6
  VARIANT_DATE                     : 0x7, // 7
  VARIANT_BSTR                     : 0x8, // 8
  VARIANT_DISPATCH                 : 0x9, // 9
  VARIANT_ERROR                    : 0xa, // 10
  VARIANT_BOOL                     : 0xb, // 11
  VARIANT_VARIANT                  : 0xc, // 12
  VARIANT_UNKNOWN                  : 0xd, // 13
  VARIANT_DECIMAL                  : 0xe, // 14
  VARIANT_I1                       : 0x10, // 16
  VARIANT_UI1                      : 0x11, // 17
  VARIANT_UI2                      : 0x12, // 18
  VARIANT_UI4                      : 0x13, // 19
  VARIANT_I8                       : 0x14, // 20
  VARIANT_UI8                      : 0x15, // 21
  VARIANT_INT                      : 0x16, // 22
  VARIANT_UINT                     : 0x17, // 23
  VARIANT_VOID                     : 0x18, // 24
  VARIANT_HRESULT                  : 0x19, // 25
  VARIANT_PTR                      : 0x1a, // 26
  VARIANT_SAFEARRAY                : 0x1b, // 27
  VARIANT_CARRAY                   : 0x1c, // 28
  VARIANT_USERDEFINED              : 0x1d, // 29
  VARIANT_LPSTR                    : 0x1e, // 30
  VARIANT_LPWSTR                   : 0x1f, // 31
  VARIANT_RECORD                   : 0x24, // 36
  VARIANT_FILETIME                 : 0x40, // 64
  VARIANT_BLOB                     : 0x41, // 65
  VARIANT_STREAM                   : 0x42, // 66
  VARIANT_STORAGE                  : 0x43, // 67
  VARIANT_STREAMED_OBJECT          : 0x44, // 68
  VARIANT_STORED_OBJECT            : 0x45, // 69
  VARIANT_BLOB_OBJECT              : 0x46, // 70
  VARIANT_CF                       : 0x47, // 71
  VARIANT_CLSID                    : 0x48, // 72
  VARIANT_VECTOR                   : 0x1000, // 4096
  VARIANT_ARRAY                    : 0x2000, // 8192
  VARIANT_BYREF                    : 0x4000, // 16384
  ZERO_LEN_ARRAY                   : 0x0, // 0
// tokentype.h
  TOKEN_MODULE           : 0x0, // 0
  TOKEN_TYPE_REF         : 0x1000000, // 16777216
  TOKEN_TYPE_DEF         : 0x2000000, // 33554432
  TOKEN_FIELD_DEF        : 0x4000000, // 67108864
  TOKEN_METHOD_DEF       : 0x6000000, // 100663296
  TOKEN_PARAM_DEF        : 0x8000000, // 134217728
  TOKEN_INTERFACE_IMPL   : 0x9000000, // 150994944
  TOKEN_MEMBER_REF       : 0xa000000, // 167772160
  TOKEN_CUSTOM_ATTRIBUTE : 0xc000000, // 201326592
  TOKEN_PERMISSION       : 0xe000000, // 234881024
  TOKEN_SIGNATURE        : 0x11000000, // 285212672
  TOKEN_EVENT            : 0x14000000, // 335544320
  TOKEN_PROPERTY         : 0x17000000, // 385875968
  TOKEN_MODULE_REF       : 0x1a000000, // 436207616
  TOKEN_TYPE_SPEC        : 0x1b000000, // 452984832
  TOKEN_ASSEMBLY         : 0x20000000, // 536870912
  TOKEN_ASSEMBLY_REF     : 0x23000000, // 587202560
  TOKEN_FILE             : 0x26000000, // 637534208
  TOKEN_EXPORTED_TYPE    : 0x27000000, // 654311424
  TOKEN_MANIFEST_RESOURCE: 0x28000000, // 671088640
  TOKEN_GENERIC_PARAM    : 0x2a000000, // 704643072
  TOKEN_METHOD_SPEC      : 0x2b000000, // 721420288
  TOKEN_STRING           : 0x70000000, // 1879048192
  TOKEN_NAME             : 0x71000000, // 1895825408
  TOKEN_BASE_TYPE        : 0x72000000, // 1912602624
// class-internals.h
  APPDOMAIN_CREATED                    : 0x0, // 0
  APPDOMAIN_UNLOADING_START            : 0x1, // 1
  APPDOMAIN_UNLOADING                  : 0x2, // 2
  APPDOMAIN_UNLOADED                   : 0x3, // 3
  BITSET_DONT_FREE                     : 0x1, // 1
  CLASS_PROP_EXCEPTION_DATA            : 0x0, // 0
  DECLSEC_ACTION_MIN                   : 0x1, // 1
  DECLSEC_FLAG_REQUEST                 : 0x1, // 1
  DECLSEC_FLAG_DEMAND                  : 0x2, // 2
  DECLSEC_FLAG_ASSERT                  : 0x4, // 4
  DECLSEC_FLAG_DENY                    : 0x8, // 8
  DECLSEC_FLAG_PERMITONLY              : 0x10, // 16
  DECLSEC_ACTION_MAX                   : 0x12, // 18
  DECLSEC_FLAG_LINKDEMAND              : 0x20, // 32
  DECLSEC_FLAG_INHERITANCEDEMAND       : 0x40, // 64
  DECLSEC_FLAG_REQUEST_MINIMUM         : 0x80, // 128
  DECLSEC_FLAG_REQUEST_OPTIONAL        : 0x100, // 256
  DECLSEC_FLAG_REQUEST_REFUSE          : 0x200, // 512
  DECLSEC_FLAG_PREJIT_GRANT            : 0x400, // 1024
  DECLSEC_FLAG_PREJIT_DENY             : 0x800, // 2048
  DECLSEC_FLAG_NONCAS_DEMAND           : 0x1000, // 4096
  DECLSEC_FLAG_NONCAS_LINKDEMAND       : 0x2000, // 8192
  DECLSEC_FLAG_NONCAS_INHERITANCEDEMAND: 0x4000, // 16384
  DECLSEC_FLAG_LINKDEMAND_CHOICE       : 0x8000, // 32768
  DECLSEC_FLAG_INHERITANCEDEMAND_CHOICE: 0x10000, // 65536
  DECLSEC_FLAG_DEMAND_CHOICE           : 0x20000, // 131072
  DEFAULT_SUPERTABLE_SIZE              : 0x6, // 6
  DEPRECATED                           : 0x1, // 1
  DL_LAZY                              : 0x1, // 1
  DL_LOCAL                             : 0x2, // 2
  DL_MASK                              : 0x3, // 3
  ERROR_NONE                           : 0x0, // 0
  ERROR_FREE_STRINGS                   : 0x1, // 1
  ERROR_MISSING_METHOD                 : 0x1, // 1
  ERROR_INCOMPLETE                     : 0x2, // 2
  ERROR_MISSING_FIELD                  : 0x2, // 2
  ERROR_TYPE_LOAD                      : 0x3, // 3
  ERROR_FILE_NOT_FOUND                 : 0x4, // 4
  ERROR_BAD_IMAGE                      : 0x5, // 5
  ERROR_OUT_OF_MEMORY                  : 0x6, // 6
  ERROR_ARGUMENT                       : 0x7, // 7
  ERROR_NOT_VERIFIABLE                 : 0x8, // 8
  ERROR_GENERIC                        : 0x9, // 9
  EXCEPTION_NONE                       : 0x0, // 0
  EXCEPTION_SECURITY_LINKDEMAND        : 0x1, // 1
  EXCEPTION_SECURITY_INHERITANCEDEMAND : 0x2, // 2
  EXCEPTION_INVALID_PROGRAM            : 0x3, // 3
  EXCEPTION_UNVERIFIABLE_IL            : 0x4, // 4
  EXCEPTION_MISSING_METHOD             : 0x5, // 5
  EXCEPTION_MISSING_FIELD              : 0x6, // 6
  EXCEPTION_TYPE_LOAD                  : 0x7, // 7
  EXCEPTION_FILE_NOT_FOUND             : 0x8, // 8
  EXCEPTION_METHOD_ACCESS              : 0x9, // 9
  EXCEPTION_FIELD_ACCESS               : 0xa, // 10
  EXCEPTION_GENERIC_SHARING_FAILED     : 0xb, // 11
  EXCEPTION_BAD_IMAGE                  : 0xc, // 12
  EXCEPTION_OBJECT_SUPPLIED            : 0xd, // 13
  EXCEPTION_OUT_OF_MEMORY              : 0xe, // 14
  GENERIC_SHARING_NONE                 : 0x0, // 0
  GENERIC_CONTEXT_USED_CLASS           : 0x1, // 1
  GENERIC_SHARING_COLLECTIONS          : 0x1, // 1
  GENERIC_CONTEXT_USED_METHOD          : 0x2, // 2
  GENERIC_SHARING_CORLIB               : 0x2, // 2
  GENERIC_CONTEXT_USED_BOTH            : 0x3, // 3
  GENERIC_SHARING_ALL                  : 0x3, // 3
  HASH_CONSERVATIVE_GC                 : 0x0, // 0
  HASH_KEY_GC                          : 0x1, // 1
  HASH_VALUE_GC                        : 0x2, // 2
  HASH_KEY_VALUE_GC                    : 0x3, // 3
  INTERNAL                             : 0x1, // 1
  JIT_INFO_TABLE_CHUNK_SIZE            : 0x40, // 64
  LLVM_INTERNAL                        : 0x1, // 1
  METHOD_PROP_GENERIC_CONTAINER        : 0x0, // 0
  PROCESSOR_ARCHITECTURE_NONE          : 0x0, // 0
  PROCESSOR_ARCHITECTURE_MSIL          : 0x1, // 1
  PROCESSOR_ARCHITECTURE_X86           : 0x2, // 2
  PROCESSOR_ARCHITECTURE_IA64          : 0x3, // 3
  PROCESSOR_ARCHITECTURE_AMD64         : 0x4, // 4
  PROP_DYNAMIC_CATTR                   : 0x1000, // 4096
  PUBLIC_KEY_TOKEN_LENGTH              : 0x11, // 17
  REMOTING_TARGET_UNKNOWN              : 0x0, // 0
  REMOTING_TARGET_APPDOMAIN            : 0x1, // 1
  REMOTING_TARGET_COMINTEROP           : 0x2, // 2
  SECTION_TEXT                         : 0x0, // 0
  SECTION_RSRC                         : 0x1, // 1
  SECTION_RELOC                        : 0x2, // 2
  SECTION_MAX                          : 0x3, // 3
  TYPE_NAME_FORMAT_IL                  : 0x0, // 0
  TYPE_NAME_FORMAT_REFLECTION          : 0x1, // 1
  TYPE_NAME_FORMAT_FULL_NAME           : 0x2, // 2
  TYPE_NAME_FORMAT_ASSEMBLY_QUALIFIED  : 0x3, // 3
  ZERO_LEN_ARRAY                       : 0x1, // 1
// tabledefs.h
  ASSEMBLY_HASH_NONE                            : 0x0, // 0
  ASSEMBLY_HASH_MD5                             : 0x8003, // 32771
  ASSEMBLY_HASH_SHA1                            : 0x8004, // 32772
  ASSEMBLYREF_FULL_PUBLIC_KEY_FLAG              : 0x1, // 1
  ASSEMBLYREF_RETARGETABLE_FLAG                 : 0x100, // 256
  ASSEMBLYREF_DISABLEJITCOMPILE_OPTIMIZER_FLAG  : 0x4000, // 16384
  ASSEMBLYREF_ENABLEJITCOMPILE_TRACKING_FLAG    : 0x8000, // 32768
  EVENT_SPECIALNAME                             : 0x200, // 512
  EVENT_RTSPECIALNAME                           : 0x400, // 1024
  FIELD_ATTRIBUTE_COMPILER_CONTROLLED           : 0x0, // 0
  FIELD_ATTRIBUTE_PRIVATE                       : 0x1, // 1
  FIELD_ATTRIBUTE_FAM_AND_ASSEM                 : 0x2, // 2
  FIELD_ATTRIBUTE_ASSEMBLY                      : 0x3, // 3
  FIELD_ATTRIBUTE_FAMILY                        : 0x4, // 4
  FIELD_ATTRIBUTE_FAM_OR_ASSEM                  : 0x5, // 5
  FIELD_ATTRIBUTE_PUBLIC                        : 0x6, // 6
  FIELD_ATTRIBUTE_FIELD_ACCESS_MASK             : 0x7, // 7
  FIELD_ATTRIBUTE_STATIC                        : 0x10, // 16
  FIELD_ATTRIBUTE_INIT_ONLY                     : 0x20, // 32
  FIELD_ATTRIBUTE_LITERAL                       : 0x40, // 64
  FIELD_ATTRIBUTE_NOT_SERIALIZED                : 0x80, // 128
  FIELD_ATTRIBUTE_HAS_FIELD_RVA                 : 0x100, // 256
  FIELD_ATTRIBUTE_SPECIAL_NAME                  : 0x200, // 512
  FIELD_ATTRIBUTE_RT_SPECIAL_NAME               : 0x400, // 1024
  FIELD_ATTRIBUTE_HAS_FIELD_MARSHAL             : 0x1000, // 4096
  FIELD_ATTRIBUTE_PINVOKE_IMPL                  : 0x2000, // 8192
  FIELD_ATTRIBUTE_HAS_DEFAULT                   : 0x8000, // 32768
  FIELD_ATTRIBUTE_RESERVED_MASK                 : 0x9500, // 38144
  FILE_CONTAINS_METADATA                        : 0x0, // 0
  FILE_CONTAINS_NO_METADATA                     : 0x1, // 1
  MANIFEST_RESOURCE_PUBLIC                      : 0x1, // 1
  MANIFEST_RESOURCE_PRIVATE                     : 0x2, // 2
  MANIFEST_RESOURCE_VISIBILITY_MASK             : 0x7, // 7
  METHOD_ATTRIBUTE_COMPILER_CONTROLLED          : 0x0, // 0
  METHOD_ATTRIBUTE_REUSE_SLOT                   : 0x0, // 0
  METHOD_IMPL_ATTRIBUTE_IL                      : 0x0, // 0
  METHOD_IMPL_ATTRIBUTE_MANAGED                 : 0x0, // 0
  METHOD_ATTRIBUTE_PRIVATE                      : 0x1, // 1
  METHOD_IMPL_ATTRIBUTE_NATIVE                  : 0x1, // 1
  METHOD_SEMANTIC_SETTER                        : 0x1, // 1
  METHOD_ATTRIBUTE_FAM_AND_ASSEM                : 0x2, // 2
  METHOD_IMPL_ATTRIBUTE_OPTIL                   : 0x2, // 2
  METHOD_SEMANTIC_GETTER                        : 0x2, // 2
  METHOD_ATTRIBUTE_ASSEM                        : 0x3, // 3
  METHOD_IMPL_ATTRIBUTE_CODE_TYPE_MASK          : 0x3, // 3
  METHOD_IMPL_ATTRIBUTE_RUNTIME                 : 0x3, // 3
  METHOD_ATTRIBUTE_FAMILY                       : 0x4, // 4
  METHOD_IMPL_ATTRIBUTE_MANAGED_MASK            : 0x4, // 4
  METHOD_IMPL_ATTRIBUTE_UNMANAGED               : 0x4, // 4
  METHOD_SEMANTIC_OTHER                         : 0x4, // 4
  METHOD_ATTRIBUTE_FAM_OR_ASSEM                 : 0x5, // 5
  METHOD_ATTRIBUTE_PUBLIC                       : 0x6, // 6
  METHOD_ATTRIBUTE_MEMBER_ACCESS_MASK           : 0x7, // 7
  METHOD_ATTRIBUTE_UNMANAGED_EXPORT             : 0x8, // 8
  METHOD_IMPL_ATTRIBUTE_NOINLINING              : 0x8, // 8
  METHOD_SEMANTIC_ADD_ON                        : 0x8, // 8
  METHOD_ATTRIBUTE_STATIC                       : 0x10, // 16
  METHOD_IMPL_ATTRIBUTE_FORWARD_REF             : 0x10, // 16
  METHOD_SEMANTIC_REMOVE_ON                     : 0x10, // 16
  METHOD_ATTRIBUTE_FINAL                        : 0x20, // 32
  METHOD_IMPL_ATTRIBUTE_SYNCHRONIZED            : 0x20, // 32
  METHOD_SEMANTIC_FIRE                          : 0x20, // 32
  METHOD_ATTRIBUTE_VIRTUAL                      : 0x40, // 64
  METHOD_IMPL_ATTRIBUTE_NOOPTIMIZATION          : 0x40, // 64
  METHOD_ATTRIBUTE_HIDE_BY_SIG                  : 0x80, // 128
  METHOD_IMPL_ATTRIBUTE_PRESERVE_SIG            : 0x80, // 128
  METHOD_ATTRIBUTE_NEW_SLOT                     : 0x100, // 256
  METHOD_ATTRIBUTE_VTABLE_LAYOUT_MASK           : 0x100, // 256
  METHOD_IMPL_ATTRIBUTE_AGGRESSIVE_INLINING     : 0x100, // 256
  METHOD_ATTRIBUTE_STRICT                       : 0x200, // 512
  METHOD_ATTRIBUTE_ABSTRACT                     : 0x400, // 1024
  METHOD_ATTRIBUTE_SPECIAL_NAME                 : 0x800, // 2048
  METHOD_ATTRIBUTE_RT_SPECIAL_NAME              : 0x1000, // 4096
  METHOD_IMPL_ATTRIBUTE_INTERNAL_CALL           : 0x1000, // 4096
  METHOD_ATTRIBUTE_PINVOKE_IMPL                 : 0x2000, // 8192
  METHOD_ATTRIBUTE_HAS_SECURITY                 : 0x4000, // 16384
  METHOD_ATTRIBUTE_REQUIRE_SEC_OBJECT           : 0x8000, // 32768
  METHOD_ATTRIBUTE_RESERVED_MASK                : 0xd000, // 53248
  METHOD_IMPL_ATTRIBUTE_MAX_METHOD_IMPL_VAL     : 0xffff, // 65535
  PARAM_ATTRIBUTE_IN                            : 0x1, // 1
  PARAM_ATTRIBUTE_OUT                           : 0x2, // 2
  PARAM_ATTRIBUTE_OPTIONAL                      : 0x10, // 16
  PARAM_ATTRIBUTE_HAS_DEFAULT                   : 0x1000, // 4096
  PARAM_ATTRIBUTE_HAS_FIELD_MARSHAL             : 0x2000, // 8192
  PARAM_ATTRIBUTE_UNUSED                        : 0xcfe0, // 53216
  PARAM_ATTRIBUTE_RESERVED_MASK                 : 0xf000, // 61440
  PINVOKE_ATTRIBUTE_CHAR_SET_NOT_SPEC           : 0x0, // 0
  PINVOKE_ATTRIBUTE_NO_MANGLE                   : 0x1, // 1
  PINVOKE_ATTRIBUTE_CHAR_SET_ANSI               : 0x2, // 2
  PINVOKE_ATTRIBUTE_CHAR_SET_UNICODE            : 0x4, // 4
  PINVOKE_ATTRIBUTE_CHAR_SET_AUTO               : 0x6, // 6
  PINVOKE_ATTRIBUTE_CHAR_SET_MASK               : 0x6, // 6
  PINVOKE_ATTRIBUTE_CALL_CONV_GENERICINST       : 0xa, // 10
  PINVOKE_ATTRIBUTE_BEST_FIT_ENABLED            : 0x10, // 16
  PINVOKE_ATTRIBUTE_CALL_CONV_GENERIC           : 0x10, // 16
  PINVOKE_ATTRIBUTE_BEST_FIT_DISABLED           : 0x20, // 32
  PINVOKE_ATTRIBUTE_BEST_FIT_MASK               : 0x30, // 48
  PINVOKE_ATTRIBUTE_SUPPORTS_LAST_ERROR         : 0x40, // 64
  PINVOKE_ATTRIBUTE_CALL_CONV_WINAPI            : 0x100, // 256
  PINVOKE_ATTRIBUTE_CALL_CONV_CDECL             : 0x200, // 512
  PINVOKE_ATTRIBUTE_CALL_CONV_STDCALL           : 0x300, // 768
  PINVOKE_ATTRIBUTE_CALL_CONV_THISCALL          : 0x400, // 1024
  PINVOKE_ATTRIBUTE_CALL_CONV_FASTCALL          : 0x500, // 1280
  PINVOKE_ATTRIBUTE_CALL_CONV_MASK              : 0x700, // 1792
  PINVOKE_ATTRIBUTE_THROW_ON_UNMAPPABLE_ENABLED : 0x1000, // 4096
  PINVOKE_ATTRIBUTE_THROW_ON_UNMAPPABLE_DISABLED: 0x2000, // 8192
  PINVOKE_ATTRIBUTE_THROW_ON_UNMAPPABLE_MASK    : 0x3000, // 12288
  PROPERTY_ATTRIBUTE_SPECIAL_NAME               : 0x200, // 512
  PROPERTY_ATTRIBUTE_RT_SPECIAL_NAME            : 0x400, // 1024
  PROPERTY_ATTRIBUTE_HAS_DEFAULT                : 0x1000, // 4096
  PROPERTY_ATTRIBUTE_UNUSED                     : 0xe9ff, // 59903
  PROPERTY_ATTRIBUTE_RESERVED_MASK              : 0xf400, // 62464
  SECURITY_ACTION_DEMAND                        : 0x2, // 2
  SECURITY_ACTION_ASSERT                        : 0x3, // 3
  SECURITY_ACTION_DENY                          : 0x4, // 4
  SECURITY_ACTION_PERMITONLY                    : 0x5, // 5
  SECURITY_ACTION_LINKDEMAND                    : 0x6, // 6
  SECURITY_ACTION_INHERITDEMAND                 : 0x7, // 7
  SECURITY_ACTION_REQMIN                        : 0x8, // 8
  SECURITY_ACTION_REQOPT                        : 0x9, // 9
  SECURITY_ACTION_REQREFUSE                     : 0xa, // 10
  SECURITY_ACTION_NONCASDEMAND                  : 0xd, // 13
  SECURITY_ACTION_NONCASLINKDEMAND              : 0xe, // 14
  SECURITY_ACTION_NONCASINHERITANCE             : 0xf, // 15
  SECURITY_ACTION_LINKDEMANDCHOICE              : 0x10, // 16
  SECURITY_ACTION_INHERITDEMANDCHOICE           : 0x11, // 17
  SECURITY_ACTION_DEMANDCHOICE                  : 0x12, // 18
  TYPE_ATTRIBUTE_ANSI_CLASS                     : 0x0, // 0
  TYPE_ATTRIBUTE_AUTO_LAYOUT                    : 0x0, // 0
  TYPE_ATTRIBUTE_CLASS                          : 0x0, // 0
  TYPE_ATTRIBUTE_NOT_PUBLIC                     : 0x0, // 0
  TYPE_ATTRIBUTE_PUBLIC                         : 0x1, // 1
  TYPE_ATTRIBUTE_NESTED_PUBLIC                  : 0x2, // 2
  TYPE_ATTRIBUTE_NESTED_PRIVATE                 : 0x3, // 3
  TYPE_ATTRIBUTE_NESTED_FAMILY                  : 0x4, // 4
  TYPE_ATTRIBUTE_NESTED_ASSEMBLY                : 0x5, // 5
  TYPE_ATTRIBUTE_NESTED_FAM_AND_ASSEM           : 0x6, // 6
  TYPE_ATTRIBUTE_NESTED_FAM_OR_ASSEM            : 0x7, // 7
  TYPE_ATTRIBUTE_VISIBILITY_MASK                : 0x7, // 7
  TYPE_ATTRIBUTE_SEQUENTIAL_LAYOUT              : 0x8, // 8
  TYPE_ATTRIBUTE_EXPLICIT_LAYOUT                : 0x10, // 16
  TYPE_ATTRIBUTE_LAYOUT_MASK                    : 0x18, // 24
  TYPE_ATTRIBUTE_CLASS_SEMANTIC_MASK            : 0x20, // 32
  TYPE_ATTRIBUTE_INTERFACE                      : 0x20, // 32
  TYPE_ATTRIBUTE_ABSTRACT                       : 0x80, // 128
  TYPE_ATTRIBUTE_SEALED                         : 0x100, // 256
  TYPE_ATTRIBUTE_SPECIAL_NAME                   : 0x400, // 1024
  TYPE_ATTRIBUTE_RT_SPECIAL_NAME                : 0x800, // 2048
  TYPE_ATTRIBUTE_IMPORT                         : 0x1000, // 4096
  TYPE_ATTRIBUTE_SERIALIZABLE                   : 0x2000, // 8192
  TYPE_ATTRIBUTE_UNICODE_CLASS                  : 0x10000, // 65536
  TYPE_ATTRIBUTE_AUTO_CLASS                     : 0x20000, // 131072
  TYPE_ATTRIBUTE_STRING_FORMAT_MASK             : 0x30000, // 196608
  TYPE_ATTRIBUTE_HAS_SECURITY                   : 0x40000, // 262144
  TYPE_ATTRIBUTE_RESERVED_MASK                  : 0x40800, // 264192
  TYPE_ATTRIBUTE_BEFORE_FIELD_INIT              : 0x100000, // 1048576
  TYPE_ATTRIBUTE_FORWARDER                      : 0x200000, // 2097152
}; // constants

/** @enum {int} */
var MetaType = {
  UINT32    : 1,
  UINT16    : 2,
  UINT8     : 3,
  BLOB_IDX  : 4,
  STRING_IDX: 5,
  GUID_IDX  : 6,
  TABLE_IDX : 7,
  CONST_IDX : 8,
  HASCAT_IDX: 9,
  CAT_IDX   : 10,
  HASDEC_IDX: 11,
  IMPL_IDX  : 12,
  HFM_IDX   : 13,
  MF_IDX    : 14,
  TDOR_IDX  : 15,
  MRP_IDX   : 16,
  MDOR_IDX  : 17,
  HS_IDX    : 18,
  RS_IDX    : 19,
}; // end of enum MetaType

/** @const {Array} */
var TableSchema = [
  { // TABLE_MODULE
    name: "Module",
    fields: [
      "Generation",
      "Name",
      "MVID",
      "EncID",
      "EncBaseID",
    ],
    field_type: [
      MetaType.UINT16,
      MetaType.STRING_IDX,
      MetaType.GUID_IDX,
      MetaType.GUID_IDX,
      MetaType.GUID_IDX,
    ],
  },
  { // TABLE_TYPEREF
    name: "TypeRef",
    fields: [
      "ResolutionScope=ResolutionScope",
      "Name",
      "Namespace",
    ],
    field_type: [
      MetaType.RS_IDX,
      MetaType.STRING_IDX,
      MetaType.STRING_IDX,
    ],
  },
  { // TABLE_TYPEDEF
    name: "TypeDef",
    fields: [
      "Flags",
      "Name",
      "Namespace",
      "Extends",
      "FieldList:Field",
      "MethodList:Method",
    ],
    field_type: [
      MetaType.UINT32,
      MetaType.STRING_IDX,
      MetaType.STRING_IDX,
      MetaType.TDOR_IDX,
      MetaType.TABLE_IDX,
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_FIELD_POINTER
    name: "FieldPtr",
    fields: [
      "Field",
    ],
    field_type: [
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_FIELD
    name: "Field",
    fields: [
      "Flags",
      "Name",
      "Signature",
    ],
    field_type: [
      MetaType.UINT16,
      MetaType.STRING_IDX,
      MetaType.BLOB_IDX,
    ],
  },
  { // TABLE_METHOD_POINTER
    name: "MethodPtr",
    fields: [
      "Method",
    ],
    field_type: [
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_METHOD
    name: "Method",
    fields: [
      "RVA",
      "ImplFlags#MethodImplAttributes",
      "Flags#MethodAttribute",
      "Name",
      "Signature",
      "ParamList:Param",
    ],
    field_type: [
      MetaType.UINT32,
      MetaType.UINT16,
      MetaType.UINT16,
      MetaType.STRING_IDX,
      MetaType.BLOB_IDX,
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_PARAM_POINTER
    name: "ParamPtr",
    fields: [
      "Param",
    ],
    field_type: [
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_PARAM
    name: "Param",
    fields: [
      "Flags",
      "Sequence",
      "Name",
    ],
    field_type: [
      MetaType.UINT16,
      MetaType.UINT16,
      MetaType.STRING_IDX,
    ],
  },
  { // TABLE_INTERFACEIMPL
    name: "InterfaceImpl",
    fields: [
      "Class:TypeDef",
      "Interface=TypeDefOrRef",
    ],
    field_type: [
      MetaType.TABLE_IDX,
      MetaType.TDOR_IDX,
    ],
  },
  { // TABLE_MEMBERREF
    name: "MemberRef",
    fields: [
      "Class",
      "Name",
      "Signature",
    ],
    field_type: [
      MetaType.MRP_IDX,
      MetaType.STRING_IDX,
      MetaType.BLOB_IDX,
    ],
  },
  { // TABLE_CONSTANT
    name: "Constant",
    fields: [
      "Type",
      "PaddingZero",
      "Parent",
      "Value",
    ],
    field_type: [
      MetaType.UINT8,
      MetaType.UINT8,
      MetaType.CONST_IDX,
      MetaType.BLOB_IDX,
    ],
  },
  { // TABLE_CUSTOMATTRIBUTE
    name: "CustomAttribute",
    fields: [
      "Parent",
      "Type",
      "Value",
    ],
    field_type: [
      MetaType.HASCAT_IDX,
      MetaType.CAT_IDX,
      MetaType.BLOB_IDX,
    ],
  },
  { // TABLE_FIELDMARSHAL
    name: "FieldMarshal",
    fields: [
      "Parent",
      "NativeType",
    ],
    field_type: [
      MetaType.HFM_IDX,
      MetaType.BLOB_IDX,
    ],
  },
  { // TABLE_DECLSECURITY
    name: "DeclSecurity",
    fields: [
      "Action",
      "Parent",
      "PermissionSet",
    ],
    field_type: [
      MetaType.UINT16,
      MetaType.HASDEC_IDX,
      MetaType.BLOB_IDX,
    ],
  },
  { // TABLE_CLASSLAYOUT
    name: "ClassLayout",
    fields: [
      "PackingSize",
      "ClassSize",
      "Parent:TypeDef",
    ],
    field_type: [
      MetaType.UINT16,
      MetaType.UINT32,
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_FIELDLAYOUT
    name: "FieldLayoutt",
    fields: [
      "Offset",
      "Field:Field",
    ],
    field_type: [
      MetaType.UINT32,
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_STANDALONESIG
    name: "StandaloneSig",
    fields: [
      "Signature",
    ],
    field_type: [
      MetaType.BLOB_IDX,
    ],
  },
  { // TABLE_EVENTMAP
    name: "EventMap",
    fields: [
      "Parent:TypeDef",
      "EventList:Event",
    ],
    field_type: [
      MetaType.TABLE_IDX,
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_EVENT_POINTER
    name: "EventPtr",
    fields: [
      "Event",
    ],
    field_type: [
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_EVENT
    name: "Event",
    fields: [
      "EventFlags#EventAttribute",
      "Name",
      "EventType",
    ],
    field_type: [
      MetaType.UINT16,
      MetaType.STRING_IDX,
      MetaType.TDOR_IDX,
    ],
  },
  { // TABLE_PROPERTYMAP
    name: "PropertyMap",
    fields: [
      "Parent:TypeDef",
      "PropertyList:Property",
    ],
    field_type: [
      MetaType.TABLE_IDX,
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_PROPERTY_POINTER
    name: "PropertyPtr",
    fields: [
      "Property",
    ],
    field_type: [
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_PROPERTY
    name: "Property",
    fields: [
      "Flags",
      "Name",
      "Type",
    ],
    field_type: [
      MetaType.UINT16,
      MetaType.STRING_IDX,
      MetaType.BLOB_IDX,
    ],
  },
  { // TABLE_METHODSEMANTICS
    name: "MethodSemantics",
    fields: [
      "MethodSemantic",
      "Method:Method",
      "Association",
    ],
    field_type: [
      MetaType.UINT16,
      MetaType.TABLE_IDX,
      MetaType.HS_IDX,
    ],
  },
  { // TABLE_METHODIMPL
    name: "MethodImpl",
    fields: [
      "Class:TypeDef",
      "MethodBody",
      "MethodDeclaration",
    ],
    field_type: [
      MetaType.TABLE_IDX,
      MetaType.MDOR_IDX,
      MetaType.MDOR_IDX,
    ],
  },
  { // TABLE_MODULEREF
    name: "Moduleref",
    fields: [
      "Name",
    ],
    field_type: [
      MetaType.STRING_IDX,
    ],
  },
  { // TABLE_TYPESPEC
    name: "TypeSpec",
    fields: [
      "Signature",
    ],
    field_type: [
      MetaType.BLOB_IDX,
    ],
  },
  { // TABLE_IMPLMAP
    name: "ImplMap",
    fields: [
      "MappingFlag",
      "MemberForwarded",
      "ImportName",
      "ImportScope:ModuleRef",
    ],
    field_type: [
      MetaType.UINT16,
      MetaType.MF_IDX,
      MetaType.STRING_IDX,
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_FIELDRVA
    name: "FieldRVA",
    fields: [
      "RVA",
      "Field:Field",
    ],
    field_type: [
      MetaType.UINT32,
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_UNUSED6
    name: "",
    fields: [
    ],
    field_type: [
    ],
  },
  { // TABLE_UNUSED7
    name: "",
    fields: [
    ],
    field_type: [
    ],
  },
  { // TABLE_ASSEMBLY
    name: "Assembly",
    fields: [
      "HashId",
      "Major",
      "Minor",
      "BuildNumber",
      "RevisionNumber",
      "Flags",
      "PublicKey",
      "Name",
      "Culture",
    ],
    field_type: [
      MetaType.UINT32,
      MetaType.UINT16,
      MetaType.UINT16,
      MetaType.UINT16,
      MetaType.UINT16,
      MetaType.UINT32,
      MetaType.BLOB_IDX,
      MetaType.STRING_IDX,
      MetaType.STRING_IDX,
    ],
  },
  { // TABLE_ASSEMBLYPROCESSOR
    name: "AssemblyProcessor",
    fields: [
      "Processor",
    ],
    field_type: [
      MetaType.UINT32,
    ],
  },
  { // TABLE_ASSEMBLYOS
    name: "AssemblyOS",
    fields: [
      "OSPlatformID",
      "OSMajor",
      "OSMinor",
    ],
    field_type: [
      MetaType.UINT32,
      MetaType.UINT32,
      MetaType.UINT32,
    ],
  },
  { // TABLE_ASSEMBLYREF
    name: "AssemblyRef",
    fields: [
      "Major",
      "Minor",
      "Build",
      "Revision",
      "Flags",
      "PublicKeyOrToken",
      "Name",
      "Culture",
      "HashValue",
    ],
    field_type: [
      MetaType.UINT16,
      MetaType.UINT16,
      MetaType.UINT16,
      MetaType.UINT16,
      MetaType.UINT32,
      MetaType.BLOB_IDX,
      MetaType.STRING_IDX,
      MetaType.STRING_IDX,
      MetaType.BLOB_IDX,
    ],
  },
  { // TABLE_ASSEMBLYREFPROCESSOR
    name: "AssemblyRefProcessor",
    fields: [
      "Processor",
      "AssemblyRef:AssemblyRef",
    ],
    field_type: [
      MetaType.UINT32,
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_ASSEMBLYREFOS
    name: "AssemblyRefOS",
    fields: [
      "OSPlatformID",
      "OSMajorVersion",
      "OSMinorVersion",
      "AssemblyRef:AssemblyRef",
    ],
    field_type: [
      MetaType.UINT32,
      MetaType.UINT32,
      MetaType.UINT32,
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_FILE
    name: "File",
    fields: [
      "Flags",
      "Name",
      "Value",
    ],
    field_type: [
      MetaType.UINT32,
      MetaType.STRING_IDX,
      MetaType.BLOB_IDX,
    ],
  },
  { // TABLE_EXPORTEDTYPE
    name: "ExportedType",
    fields: [
      "Flags",
      "TypeDefId",
      "TypeName",
      "TypeNameSpace",
      "Implementation",
    ],
    field_type: [
      MetaType.UINT32,
      MetaType.TABLE_IDX,
      MetaType.STRING_IDX,
      MetaType.STRING_IDX,
      MetaType.IMPL_IDX,
    ],
  },
  { // TABLE_MANIFESTRESOURCE
    name: "ManifestResource",
    fields: [
      "Offset",
      "Flags",
      "Name",
      "Implementation",
    ],
    field_type: [
      MetaType.UINT32,
      MetaType.UINT32,
      MetaType.STRING_IDX,
      MetaType.IMPL_IDX,
    ],
  },
  { // TABLE_NESTEDCLASS
    name: "NestedClass",
    fields: [
      "NestedClass:TypeDef",
      "EnclosingClass:TypeDef",
    ],
    field_type: [
      MetaType.TABLE_IDX,
      MetaType.TABLE_IDX,
    ],
  },
  { // TABLE_GENERICPARAM
    name: "GenericParam",
    fields: [
      "Number",
      "Flags",
      "Owner",
      "Name",
    ],
    field_type: [
      MetaType.UINT16,
      MetaType.UINT16,
      MetaType.TABLE_IDX,
      MetaType.STRING_IDX,
    ],
  },
  { // TABLE_METHODSPEC
    name: "MethodSpec",
    fields: [
      "Method",
      "Signature",
    ],
    field_type: [
      MetaType.MDOR_IDX,
      MetaType.BLOB_IDX,
    ],
  },
  { // TABLE_GENERICPARAMCONSTRAINT
    name: "GenericParamConstraint",
    fields: [
      "GenericParam",
      "Constraint",
    ],
    field_type: [
      MetaType.TABLE_IDX,
      MetaType.TDOR_IDX,
    ],
  },
]; // end of TableSchema
exports.TableSchema = TableSchema;
exports.MetaType    = MetaType;
exports.C           = C;
