/*
 This file is automatically generated by tool/meta.PL.
 */
// module meta
"use strict";
var __c = 0;
/** @enum {int} */
var MetaType = {
    UINT32: ++__c,
    UINT16: ++__c,
    UINT8: ++__c,

    BLOB_IDX: ++__c,
    STRING_IDX: ++__c,
    GUID_IDX: ++__c,
    TABLE_IDX: ++__c,
    CONST_IDX: ++__c,   // HashConstant:Parent
    HASCAT_IDX: ++__c,  // HasCustomAttribute
    CAT_IDX: ++__c,     // CustomAttributeType
    HASDEC_IDX: ++__c,  // HasDeclSecurity
    IMPL_IDX: ++__c,    // Implementation
    HFM_IDX: ++__c,     // HasFieldMarshal
    MF_IDX: ++__c,      // MemberFormat
    TDOR_IDX: ++__c,    // TypeDefOrRef
    MRP_IDX: ++__c,     // MemberRefParent
    MDOR_IDX: ++__c,    // MethodDefOrRef
    HS_IDX: ++__c,      // HasSemantic
    RS_IDX: ++__c       // ResolutionScope
};
/** @const {Array} */
var TableSchema = [
    {
        name: "Module",
        fields: [
            ["Generation", MetaType.UINT16],
            ["Name", MetaType.STRING_IDX],
            ["MVID", MetaType.GUID_IDX],
            ["EncID", MetaType.GUID_IDX],
            ["EncBaseID", MetaType.GUID_IDX],
        ],
    },
    {
        name: "TypeRef",
        fields: [
            ["Name", MetaType.STRING_IDX],
            ["Namespace", MetaType.STRING_IDX],
        ],
    },
    {
        name: "TypeDef",
        fields: [
            ["Flags", MetaType.UINT32],
            ["Name", MetaType.STRING_IDX],
            ["Namespace", MetaType.STRING_IDX],
            ["Extends", MetaType.TDOR_IDX],
        ],
    },
    {
        name: "FieldPtr",
        fields: [
            ["Field", MetaType.TABLE_IDX],
        ],
    },
    {
        name: "Field",
        fields: [
            ["Flags", MetaType.UINT16],
            ["Name", MetaType.STRING_IDX],
            ["Signature", MetaType.BLOB_IDX],
        ],
    },
    {
        name: "MethodPtr",
        fields: [
            ["Method", MetaType.TABLE_IDX],
        ],
    },
    {
        name: "Method",
        fields: [
            ["RVA", MetaType.UINT32],
            ["Name", MetaType.STRING_IDX],
            ["Signature", MetaType.BLOB_IDX],
        ],
    },
    {
        name: "ParamPtr",
        fields: [
            ["Param", MetaType.TABLE_IDX],
        ],
    },
    {
        name: "Param",
        fields: [
            ["Flags", MetaType.UINT16],
            ["Sequence", MetaType.UINT16],
            ["Name", MetaType.STRING_IDX],
        ],
    },
    {
        name: "InterfaceImpl",
        fields: [
        ],
    },
    {
        name: "MemberRef",
        fields: [
            ["Class", MetaType.MRP_IDX],
            ["Name", MetaType.STRING_IDX],
            ["Signature", MetaType.BLOB_IDX],
        ],
    },
    {
        name: "Constant",
        fields: [
            ["Type", MetaType.UINT8],
            ["PaddingZero", MetaType.UINT8],
            ["Parent", MetaType.CONST_IDX],
            ["Value", MetaType.BLOB_IDX],
        ],
    },
    {
        name: "CustomAttribute",
        fields: [
            ["Parent", MetaType.HASCAT_IDX],
            ["Type", MetaType.CAT_IDX],
            ["Value", MetaType.BLOB_IDX],
        ],
    },
    {
        name: "FieldMarshal",
        fields: [
            ["Parent", MetaType.HFM_IDX],
            ["NativeType", MetaType.BLOB_IDX],
        ],
    },
    {
        name: "DeclSecurity",
        fields: [
            ["Action", MetaType.UINT16],
            ["Parent", MetaType.HASDEC_IDX],
            ["PermissionSet", MetaType.BLOB_IDX],
        ],
    },
    {
        name: "ClassLayout",
        fields: [
            ["PackingSize", MetaType.UINT16],
            ["ClassSize", MetaType.UINT32],
        ],
    },
    {
        name: "FieldLayoutt",
        fields: [
            ["Offset", MetaType.UINT32],
        ],
    },
    {
        name: "StandaloneSig",
        fields: [
            ["Signature", MetaType.BLOB_IDX],
        ],
    },
    {
        name: "EventMap",
        fields: [
        ],
    },
    {
        name: "EventPtr",
        fields: [
            ["Event", MetaType.TABLE_IDX],
        ],
    },
    {
        name: "Event",
        fields: [
            ["Name", MetaType.STRING_IDX],
            ["EventType", MetaType.TDOR_IDX],
        ],
    },
    {
        name: "PropertyMap",
        fields: [
        ],
    },
    {
        name: "PropertyPtr",
        fields: [
            ["Property", MetaType.TABLE_IDX],
        ],
    },
    {
        name: "Property",
        fields: [
            ["Flags", MetaType.UINT16],
            ["Name", MetaType.STRING_IDX],
            ["Type", MetaType.BLOB_IDX],
        ],
    },
    {
        name: "MethodSemantics",
        fields: [
            ["MethodSemantic", MetaType.UINT16],
            ["Association", MetaType.HS_IDX],
        ],
    },
    {
        name: "MethodImpl",
        fields: [
            ["MethodBody", MetaType.MDOR_IDX],
            ["MethodDeclaration", MetaType.MDOR_IDX],
        ],
    },
    {
        name: "Moduleref",
        fields: [
            ["Name", MetaType.STRING_IDX],
        ],
    },
    {
        name: "TypeSpec",
        fields: [
            ["Signature", MetaType.BLOB_IDX],
        ],
    },
    {
        name: "ImplMap",
        fields: [
            ["MappingFlag", MetaType.UINT16],
            ["MemberForwarded", MetaType.MF_IDX],
            ["ImportName", MetaType.STRING_IDX],
        ],
    },
    {
        name: "FieldRVA",
        fields: [
            ["RVA", MetaType.UINT32],
        ],
    },
    {
        name: "",
        fields: [
        ],
    },
    {
        name: "",
        fields: [
        ],
    },
    {
        name: "Assembly",
        fields: [
            ["HashId", MetaType.UINT32],
            ["Major", MetaType.UINT16],
            ["Minor", MetaType.UINT16],
            ["BuildNumber", MetaType.UINT16],
            ["RevisionNumber", MetaType.UINT16],
            ["Flags", MetaType.UINT32],
            ["PublicKey", MetaType.BLOB_IDX],
            ["Name", MetaType.STRING_IDX],
            ["Culture", MetaType.STRING_IDX],
        ],
    },
    {
        name: "AssemblyProcessor",
        fields: [
            ["Processor", MetaType.UINT32],
        ],
    },
    {
        name: "AssemblyOS",
        fields: [
            ["OSPlatformID", MetaType.UINT32],
            ["OSMajor", MetaType.UINT32],
            ["OSMinor", MetaType.UINT32],
        ],
    },
    {
        name: "AssemblyRef",
        fields: [
            ["Major", MetaType.UINT16],
            ["Minor", MetaType.UINT16],
            ["Build", MetaType.UINT16],
            ["Revision", MetaType.UINT16],
            ["Flags", MetaType.UINT32],
            ["PublicKeyOrToken", MetaType.BLOB_IDX],
            ["Name", MetaType.STRING_IDX],
            ["Culture", MetaType.STRING_IDX],
            ["HashValue", MetaType.BLOB_IDX],
        ],
    },
    {
        name: "AssemblyRefProcessor",
        fields: [
            ["Processor", MetaType.UINT32],
        ],
    },
    {
        name: "AssemblyRefOS",
        fields: [
            ["OSPlatformID", MetaType.UINT32],
            ["OSMajorVersion", MetaType.UINT32],
            ["OSMinorVersion", MetaType.UINT32],
        ],
    },
    {
        name: "File",
        fields: [
            ["Flags", MetaType.UINT32],
            ["Name", MetaType.STRING_IDX],
            ["Value", MetaType.BLOB_IDX],
        ],
    },
    {
        name: "ExportedType",
        fields: [
            ["Flags", MetaType.UINT32],
            ["TypeDefId", MetaType.TABLE_IDX],
            ["TypeName", MetaType.STRING_IDX],
            ["TypeNameSpace", MetaType.STRING_IDX],
            ["Implementation", MetaType.IMPL_IDX],
        ],
    },
    {
        name: "ManifestResource",
        fields: [
            ["Offset", MetaType.UINT32],
            ["Flags", MetaType.UINT32],
            ["Name", MetaType.STRING_IDX],
            ["Implementation", MetaType.IMPL_IDX],
        ],
    },
    {
        name: "NestedClass",
        fields: [
        ],
    },
    {
        name: "GenericParam",
        fields: [
            ["Number", MetaType.UINT16],
            ["Flags", MetaType.UINT16],
            ["Owner", MetaType.TABLE_IDX],
            ["Name", MetaType.STRING_IDX],
        ],
    },
    {
        name: "MethodSpec",
        fields: [
            ["Method", MetaType.MDOR_IDX],
            ["Signature", MetaType.BLOB_IDX],
        ],
    },
    {
        name: "GenericParamConstraint",
        fields: [
            ["GenericParam", MetaType.TABLE_IDX],
            ["Constraint", MetaType.TDOR_IDX],
        ],
    },
]; // end of TableSchema
exports.TableSchema = TableSchema;
exports.MetaType    = MetaType;
